fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
  
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    type:     annotation
    prefix: /profile
  
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    type:     annotation
    prefix: /register
  
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    type:     annotation
    prefix: /resetting
  
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
     
app:
    resource: '@AppBundle/Controller/'
    type: annotation